### ISSUE TITLE
CSVの情報をseedで各テーブルに入れる

### ISSUE THREAD

**Issue by mayu-tateno** [morning-study-party/hatsunetsu-kun#24]
## 概要
rails db:seedコマンドで入れるか、gemのseed_fuを使用するか要相談。
seed_fuを利用するメリットとしては、一度作成したデータを2回目以降作成しないような設定があったはずであることです。(調査中です :bowing_woman: )

**Comment by miloneko** [comment]
seed_fuを使用する（環境ごとにseedファイルをわけれるなどのメリットがある）
