### ISSUE TITLE
LineBotControllerでのメッセージのインデントについて

### ISSUE THREAD

**Issue by yusukedayo** [morning-study-party/hatsunetsu-kun#30]
## 問題点
現状だとline_bot_controllerが以下のようにインデント見にくいなと思いました。
```ruby
class LineBotController < ApplicationController
    events = client.parse_events_from(body)
    events.each do |event|
      case event
      when Line::Bot::Event::Message
        case event.type
        when Line::Bot::Event::MessageType::Text
          message = {
            type: 'text',
            text: event.message['text']
          }
          if /移動手段（かかりつけ医がいる方）/.match?(event.message['text'])
            message = {
              "type": 'text',
              "text": "移動手段を以下の手順で検討してみてください
1.自家用車がある場合
自家用車でのご移動をお願いします
2.自家用車がない場合
発熱タクシー（有料）をご検討ください
発熱タクシーのURL
3.公共交通機関を利用の場合
もし公共交通機関を利用する場合は感染対策を徹底して人と距離をとり移動すること
4.上記の移動手段が困難な場合
救急車をご検討ください。救急車を呼ぶか迷った場合はこちらを参照ください。
参考記事のurl"
```
実際にコード変更している時のendのずれなどで苦労したので改善したいです。

## 改善方法
インデントでずらさなくても改行コードを使えばメッセージを綺麗に揃えることはできそうです。
検証はまだできてないです。
[メッセージ内の改行コードを教えてください。](https://www.line-community.me/ja/question/615c05a4d5929a59913c9f1b/%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8%E5%86%85%E3%81%AE%E6%94%B9%E8%A1%8C%E3%82%B3%E3%83%BC%E3%83%89%E3%82%92%E6%95%99%E3%81%88%E3%81%A6%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84#:~:text=%5Cn%20%E3%81%8C%E6%94%B9%E8%A1%8C%E3%82%B3%E3%83%BC%E3%83%89%E3%81%A7%E3%81%99%E3%80%82)

**Comment by miloneko** [comment]
ゆうすけさんありがとうございます！こちら今の開発ブランチで対応します！

**Comment by yusukedayo** [comment]
助かります！あざます！
