### ISSUE TITLE
データ整形

### ISSUE THREAD

**Issue by mayu-tateno** [morning-study-party/hatsunetsu-kun#4]
- 緯度・経度の情報を取得し、CSV化する→geocorderを使用してDB保存時に登録する。
# Hospitals(病院)テーブル
- [x] id(integer)
- [x] name(string)
- [x] contact(string)：以下の電話番号など分けずに、１つのカラムに全部入れてしまう。
- phone_number(integer)
- url(string)
- email(string)
  - 8/24データ変更に沿って、phone_numberとurlに出力しなおす。
- [x] notification(text)
- [x] primary_care_doctor(enum)
- [x] address(string)
- [x] holiday_support(enum)
- [x] ローカル用100件
# Business_hours (対応時間)テーブル
- [x] 月曜AM/PM
- [x] 火曜AM/PM
- [x] 水曜AM/PM
- [x] 木曜AM/PM
- [x] 金曜AM/PM
- [x] 土曜AM/PM
- [x] 日曜AM/PM
- [x] 縦に結合→合計37,148件
- [x] time型の検証（pandasでtime型に整形→csv読み込みを試す。）
- close_atがnullのカラムは、その病院のHPで情報を確認して埋める。（→8/24データ更新に伴い作業不要となった）
# ほかテーブル
- [x] Target_groups (対象者)
- [x] Inspection_types (検査の種類)
- Languages (言語)：データ混在。後回し。
- Hospitals_Languages (言語中間テーブル)：Languages (言語)作成後着手する。
# データ更新
- 8/17, 8/24, 8/31, 9/7

**Comment by yamashita-a420** [comment]
# time型の検証

### 結果
railsでtime型として扱いたいBusinessHoursテーブルのopen_at、close_atカラムについて
pandasではobject型のまま、csv読み込みを試した結果、Time型として扱えることを確認しました。
＜all＞
<img width="663" alt="image" src="https://user-images.githubusercontent.com/95392247/188317582-407c9a88-0ceb-43cb-b3a9-c0691f95ced5.png">
＜Time型のメソッドとクラスの確認＞
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/95392247/188318091-185e59bf-015a-4a4a-9def-b63410b7a5e2.png">

### 検証方法
1. migrationファイル記述後、rails db:migrate
```ruby
class CreateHospitals < ActiveRecord::Migration[6.1]
  def change
    create_table :hospitals do |t|
      t.string :name, null: false
      t.integer :phone_number
      t.string :url
      t.text :notification
      t.integer :primary_care_doctor, default: 0, null: false
      t.string :address, null: false
      t.integer :holiday_support, default: 0, null: false
      t.float :latitude, null: false
      t.float :longitude, null: false

      t.timestamps
    end
  end
end
```
```ruby
class BusinessHours < ActiveRecord::Migration[6.1]
  def change
    create_table :business_hours do |t|
      t.time :open_at, null: false
      t.time :close_at, null: false
      t.integer :meridian, default: 0, null: false
      t.integer :day_of_week, default: 0, null: false
      # 外部キー制約エラーがでたので、foreign_key: trueを外して検証
      t.references :hospital, null: false

      t.timestamps
    end
  end
end
```
2. seeds.rb記述後、csvファイルを配置してrails db:seed
```ruby
require "csv"

# ファイルを1行ずつ読み込んでコンマ区切りの配列で取得する
business_hours_csv = CSV.readlines("db/business_hours_100.csv")
# 一番上の行はカラムの説明なので削除
business_hours_csv.shift
business_hours_csv.each do |row|
  BusinessHour.create(open_at: row[1], close_at: row[2], meridian: row[3], day_of_week: row[4], hospital_id: row[5])
end
```
